version: '3'

services:
  contact-backend:
    build: .
    image: ghcr.io/tdtuan97/contact-backend:latest
    container_name: contact_backend_node
    restart: always
    env_file:
      - .env
      - .env.production
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway'
    networks:
      - contact-backend-network

  contact-backend-nginx:
    build:
      context: ./deploy/nginx
      dockerfile: Dockerfile
    container_name: contact_backend_nginx
    restart: unless-stopped
    tty: true
    ports:
      # - "80:80"
      - "7001:443"
      - "7002:444"
    volumes:
      - ./logs/nginx/:/var/logs/nginx/
      - ./deploy/nginx/conf.d/:/etc/nginx/conf.d/
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- /etc/letsencrypt/live/dev-backend-api.rabbitevc.vn/fullchain.pem:/etc/nginx/ssl/cert.pem
      #- /etc/letsencrypt/live/dev-backend-api.rabbitevc.vn/privkey.pem:/etc/nginx/ssl/private.pem
    depends_on:
      - contact-backend
    networks:
      - contact-backend-network
networks:
  contact-backend-network:
